use crossterm::event::{KeyCode, KeyEvent};
use ratatui::{layout::{Constraint, Layout, Rect}, style::{Modifier, Style}, text::Line, widgets::{Block, Borders, Padding, Paragraph}, Frame};
use tui_textarea::TextArea;
use cyber_core::MemoryRule;
use crate::theme::Theme;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryRuleFormAction { None, Save, Cancel }
pub struct MemoryRuleFormState { pub index: Option<usize>, pub enabled: bool, pub scope: String, pub prompt: String, pub editing: bool, pub textarea: TextArea<'static> }
impl MemoryRuleFormState { pub fn new(index: Option<usize>, rule: Option<&MemoryRule>) -> Self { let mut textarea=TextArea::default(); textarea.set_placeholder_text("输入自然语言规则"); Self { index, enabled: rule.map(|r|r.enabled).unwrap_or(true), scope: rule.map(|r|r.scope.clone()).unwrap_or_else(||"both".into()), prompt: rule.map(|r|r.prompt.clone()).unwrap_or_default(), editing:true, textarea } } pub fn handle_key(&mut self,k:KeyEvent)->MemoryRuleFormAction { if self.editing { match k.code { KeyCode::Enter=>{self.prompt=self.textarea.lines().join("\n");self.editing=false;MemoryRuleFormAction::None},KeyCode::Esc=>MemoryRuleFormAction::Cancel,_=>{self.textarea.input(k);MemoryRuleFormAction::None} } } else { match k.code { KeyCode::Left|KeyCode::Right=>{self.scope=match self.scope.as_str(){"global"=>"project","project"=>"both",_=>"global"}.into();MemoryRuleFormAction::None},KeyCode::Enter=>MemoryRuleFormAction::Save,KeyCode::Char('e')=>{self.textarea.clear();self.textarea.insert_str(&self.prompt);self.editing=true;MemoryRuleFormAction::None},KeyCode::Esc=>MemoryRuleFormAction::Cancel,_=>MemoryRuleFormAction::None} } } pub fn prepare_render(&mut self,theme:&Theme){self.textarea.set_block(Block::default().borders(Borders::ALL).title("规则提示").border_style(Style::default().fg(theme.border)));self.textarea.set_style(Style::default().fg(theme.fg).bg(theme.bg));} }
pub fn render(frame:&mut Frame,area:Rect,theme:&Theme,state:&MemoryRuleFormState){let modal=centered_rect(80,70,area);let block=Block::default().borders(Borders::ALL).border_style(Style::default().fg(theme.accent)).title(Line::from(" Memory Rule ").style(Style::default().fg(theme.title).add_modifier(Modifier::BOLD))).padding(Padding::new(2,2,1,1));let inner=block.inner(modal);frame.render_widget(block,modal);let c=Layout::vertical([Constraint::Length(2),Constraint::Min(5),Constraint::Length(2)]).split(inner);frame.render_widget(Paragraph::new(format!("作用域：{} (←/→ 切换)",state.scope)).style(Style::default().fg(theme.fg)),c[0]);if state.editing{frame.render_widget(&state.textarea,c[1])}else{frame.render_widget(Paragraph::new(state.prompt.as_str()).style(Style::default().fg(theme.fg)),c[1])}frame.render_widget(Paragraph::new(if state.editing{"Enter 完成编辑 Esc 取消"}else{"e 编辑 Enter 保存 Esc 取消"}).style(Style::default().fg(theme.muted)),c[2]);}
fn centered_rect(x:u16,y:u16,a:Rect)->Rect{let v=Layout::vertical([Constraint::Percentage(y)]).split(a)[0];Layout::horizontal([Constraint::Percentage(x)]).split(v)[0]}